/**
 * Client-side Markdown builder for the campaign dashboard's "Download report"
 * button. Operates on the already-mapped {@link WebCampaignResult} (0..100
 * values), so it never imports engine internals into the browser bundle.
 */
import type { WebCampaignResult } from './types';

function signed(n: number): string {
  return `${n >= 0 ? '+' : ''}${n}`;
}

/** Escape a string for a Markdown table cell: backslash, then pipe, then collapse line breaks. */
function escapePipe(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/[\r\n]+/g, ' ');
}

export function webCampaignToMarkdown(r: WebCampaignResult): string {
  const L: string[] = [];
  L.push(`# AI Visibility Report — ${r.brand}`);
  L.push('');
  L.push(`**Campaign:** ${r.campaignName}`);
  L.push(`**Generated:** ${r.generatedAt}`);
  L.push(`**AI Visibility Score:** ${r.visibilityScore}/100`);
  if (r.runCount > 1) {
    L.push(`**Since first run:** ${signed(r.visibilityDelta)} visibility · ${signed(r.shareOfVoiceDelta)}% share of voice`);
  }
  L.push('');

  L.push('## Share of voice over time');
  L.push('');
  L.push('| Date | Visibility | Share of voice |');
  L.push('|---|---:|---:|');
  for (const p of r.trend) L.push(`| ${p.date} | ${p.visibility}/100 | ${p.shareOfVoice}% |`);
  L.push('');

  L.push('## Per-engine breakdown');
  L.push('');
  L.push('| Engine | Score | Mention rate | Citation rate |');
  L.push('|---|---:|---:|---:|');
  for (const e of r.engineBreakdown) {
    L.push(`| ${escapePipe(e.engine)} | ${e.score}/100 | ${e.mentionRate}% | ${e.citationRate}% |`);
  }
  L.push('');

  if (r.competitors.length) {
    L.push('## Competitor comparison');
    L.push('');
    L.push('| Brand | Share of voice | Gap vs you |');
    L.push('|---|---:|---:|');
    for (const c of r.competitors) {
      const label = c.isTracked ? `${c.brand} (you)` : c.brand;
      const gap = c.isTracked ? '—' : `${signed(c.gapVsTracked)}%`;
      L.push(`| ${escapePipe(label)} | ${c.shareOfVoice}% | ${gap} |`);
    }
    L.push('');
  }

  L.push('## Per-prompt drill-down');
  L.push('');
  L.push('| Prompt | Score | Mentions | Citations |');
  L.push('|---|---:|---:|---:|');
  for (const p of r.prompts) {
    L.push(`| ${escapePipe(p.prompt)} | ${p.score}/100 | ${p.mentions} | ${p.citations.length} |`);
  }
  L.push('');

  L.push('---');
  L.push('');
  L.push('_Generated by gh-ai-rank-tracker._');
  L.push('');
  return L.join('\n');
}
