/**
 * Markdown export for a campaign run + trend.
 *
 * Produces a self-contained report: headline score, share-of-voice trend,
 * per-engine breakdown, competitor comparison and a per-prompt table. Pure
 * string assembly — no I/O.
 */
import type { CampaignRun } from "../campaign";
import type { Trend } from "../trends";

function pct01(n: number): string {
  return `${Math.round(n * 100)}%`;
}

function signed(n: number): string {
  return `${n >= 0 ? "+" : ""}${n}`;
}

/**
 * Make an untrusted string safe inside a Markdown table cell: escape backslash
 * *first* (so a literal `\|` doesn't become `\\|`), then the pipe, then collapse
 * any line break to a space (a raw newline would terminate the table row early).
 */
function escapeCell(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/[\r\n]+/g, " ");
}

/** Collapse line breaks for an inline (heading / bold) interpolation. */
function inline(s: string): string {
  return s.replace(/[\r\n]+/g, " ");
}

/** Render a campaign run + trend as a Markdown report. */
export function renderCampaignMarkdown(
  run: CampaignRun,
  trend: Trend,
  campaignName?: string,
): string {
  const name = campaignName ?? run.campaignId;
  const L: string[] = [];

  L.push(`# AI Visibility Report — ${inline(run.brand)}`);
  L.push("");
  L.push(`**Campaign:** ${inline(name)}`);
  L.push(`**Generated:** ${run.generatedAt}`);
  L.push(`**AI Visibility Score:** ${run.visibilityScore}/100`);
  if (trend.points.length > 1) {
    L.push(
      `**Since first run:** ${signed(trend.visibilityDelta)} visibility · ` +
        `${signed(Math.round(trend.shareOfVoiceDelta * 100))}% share of voice`,
    );
  }
  L.push("");

  // ── Trend ──────────────────────────────────────────────────────────────────
  L.push("## Share of voice over time");
  L.push("");
  L.push("| Date | Visibility | Share of voice |");
  L.push("|---|---:|---:|");
  for (const p of trend.points) {
    L.push(`| ${p.generatedAt} | ${p.visibilityScore}/100 | ${pct01(p.shareOfVoice)} |`);
  }
  L.push("");

  // ── Per-engine breakdown ─────────────────────────────────────────────────────
  L.push("## Per-engine breakdown");
  L.push("");
  L.push("| Engine | Score | Mention rate | Citation rate |");
  L.push("|---|---:|---:|---:|");
  for (const e of run.engineBreakdown) {
    L.push(`| ${escapeCell(e.engine)} | ${e.score}/100 | ${pct01(e.mentionRate)} | ${pct01(e.citationRate)} |`);
  }
  L.push("");

  // ── Competitor comparison ────────────────────────────────────────────────────
  if (run.competitorComparison.length) {
    L.push("## Competitor comparison");
    L.push("");
    L.push("| Brand | Share of voice | Gap vs you |");
    L.push("|---|---:|---:|");
    for (const c of run.competitorComparison) {
      const label = c.isTracked ? `${c.brand} (you)` : c.brand;
      const gap = c.isTracked ? "—" : `${signed(Math.round(c.gapVsTracked * 100))}%`;
      L.push(`| ${escapeCell(label)} | ${pct01(c.shareOfVoice)} | ${gap} |`);
    }
    L.push("");
  }

  // ── Per-prompt drill-down ────────────────────────────────────────────────────
  L.push("## Per-prompt drill-down");
  L.push("");
  L.push("| Prompt | Weight | Score | Mentioned | Cited |");
  L.push("|---|---:|---:|:---:|:---:|");
  for (const p of run.report.prompts) {
    L.push(
      `| ${escapeCell(p.prompt)} | ${p.weight} | ${p.score}/100 | ` +
        `${p.mentionedAnywhere ? "yes" : "—"} | ${p.citedAnywhere ? "yes" : "—"} |`,
    );
  }
  L.push("");

  // ── Recommendations ──────────────────────────────────────────────────────────
  if (run.report.recommendations.length) {
    L.push("## Recommendations");
    L.push("");
    for (const r of run.report.recommendations) {
      L.push(`- **[${r.severity.toUpperCase()}]** ${inline(r.message)}`);
    }
    L.push("");
  }

  L.push("---");
  L.push("");
  L.push("_Generated by gh-ai-rank-tracker._");
  L.push("");

  return L.join("\n");
}
